name: Kumbukaa Local
values:
  - key: baseUrl
    value: 'http://localhost:8080/kumbukaa'
  - key: token
    value: ''
  - key: refreshToken
    value: ''
  - key: authId
    value: ''
  - key: userId
    value: ''
  - key: lenderUserId
    value: ''
  - key: borrowerUserId
    value: ''
  - key: loanId
    value: ''
  - key: transactionId
    value: ''
